// Generated by CoffeeScript 1.7.1

/*
    Author: Dalston Xu
    Website: http://xuxun.me
    Updated: 2014年5月1日16:08:26

    Inspired By: http://raining.fm
    For:  Eason guo.lu
 */


/* 
    Rainy Day 
    http://maroslaw.github.io/rainyday.js/
 */


/* background image - type1 - RainyDay */

(function () {
  var bg_image_loading, bg_img_1, bg_music, bg_music_mobile, img_load_js;

  bg_img_1 = function () {
    var image;
    image = document.getElementById('background');
    image.onload = function () {
      var engine;
      engine = new RainyDay({
        image: this
      });
      engine.trail = engine.TRAIL_SMUDGE;
      return engine.rain([[1, 0, 100], [3, 3, 1], [1, 4, 20]], 100);
    };
    image.crossOrigin = 'anonymous';
    return image.src = './images/rain1.jpg';
  };


  /* background image - gif */

  img_load_js = './lib/imageprogress.js';

  document.body.classList.add('loading');

  bg_image_loading = function (imgName) {
    return $.getScript(img_load_js, function () {
      return loadImage('./images/' + imgName);
    });
  };


  /* 
      SoundManager 
      http://www.schillmania.com/projects/soundmanager2/
   */


  /* background music - type 1 - RainyDay */

  bg_music = function () {
    var MUSIC_LIST, audioSpan, audio_rain, audio_thunder_l, audio_thunder_s, music_player, pause, thunderLoudEnd, thunderSmallEnd;
    audio_rain = 'audio/rainfade_1.mp3';
    audio_thunder_s = 'audio/thunderfade_1.mp3';
    audio_thunder_l = 'audio/loudthunderfade_1.mp3';
    audioSpan = 7288;
    thunderSmallEnd = 24 * 1e3;
    thunderLoudEnd = 35200;
    MUSIC_LIST = this;
    MUSIC_LIST.rain1 = null;
    MUSIC_LIST.rain2 = null;
    MUSIC_LIST.thunder_small1 = null;
    MUSIC_LIST.thunder_small2 = null;
    MUSIC_LIST.thunder_loud1 = null;
    MUSIC_LIST.thunder_loud2 = null;
    pause = false;
    music_player = function () {
      MUSIC_LIST.rain1 = soundManager.createSound({
        id: 'rain1',
        url: audio_rain,
        autoLoad: true,
        multiShotEvents: true,
        onload: function () {
          return this.play({
            position: 0,
            loops: 3
          });
        },
        onfinish: function () {
          return this.play({
            position: 0
          });
        }
      });
      MUSIC_LIST.rain2 = soundManager.createSound({
        id: 'rain2',
        url: audio_rain,
        autoLoad: true,
        multiShotEvents: true,
        onload: function () {
          return this.play({
            volume: 0,
            position: audioSpan,
            loops: 3
          });
        },
        onfinish: function () {
          return this.play({
            position: 0
          });
        },
        onplay: function () {
          var e, i, n, r;
          if (pause) {
            return false;
          }
          e = 3 * 1e3;
          n = 0;
          r = 100;
          return i = setInterval(function () {
            var t;
            rain2.setVolume((1 + n) * (r / 12));
            n++;
            if (n === 12) {
              clearInterval(i);
              return t = true;
            }
          }, e / 12);
        }
      });

      /* 避免雷声自动播放 */
      MUSIC_LIST.thunder_small1 = soundManager.createSound({
        id: "thunder_small1",
        url: audio_thunder_s,
        onload: function () {
          return this.onPosition(thunderSmallEnd, function () {
            return thunder_small2.play({
              position: 0
            });
          });
        }
      });
      MUSIC_LIST.thunder_small2 = soundManager.createSound({
        id: "thunder_small2",
        url: audio_thunder_s,
        onload: function () {
          return this.onPosition(thunderSmallEnd, function () {
            return thunder_small1.play({
              position: 0
            });
          });
        }
      });
      MUSIC_LIST.thunder_loud1 = soundManager.createSound({
        id: "thunder_loud1",
        url: audio_thunder_l,
        onload: function () {
          return this.onPosition(thunderLoudEnd, function () {
            return thunder_loud2.play({
              position: 0
            });
          });
        }
      });
      MUSIC_LIST.thunder_loud2 = soundManager.createSound({
        id: "thunder_loud2",
        url: audio_thunder_l,
        onload: function () {
          return this.onPosition(thunderLoudEnd, function () {
            return thunder_loud1.play({
              position: 0
            });
          });
        }
      });
      $("#rainOn").click(function (e) {
        MUSIC_LIST.rain1.play();
        MUSIC_LIST.rain2.play({
          volume: 0,
          position: audioSpan
        });
        pause = false;
        $(this).closest("ul").addClass("clicked");
        return e.preventDefault();
      });
      $("#rainOff").click(function (e) {
        MUSIC_LIST.rain1.stop();
        MUSIC_LIST.rain2.stop();
        $(this).closest("ul").removeClass("clicked");
        return e.preventDefault();
      });
      $("#thunderOff").click(function (e) {
        MUSIC_LIST.thunder_small1.stop();
        MUSIC_LIST.thunder_small2.stop();
        $(this).closest("ul").removeClass("clicked");
        return e.preventDefault();
      });
      $("#thunderOn").click(function (e) {
        MUSIC_LIST.thunder_small1.play({
          position: 0
        });
        $(this).closest("ul").addClass("clicked");
        return e.preventDefault();
      });
      $("#loudThunderOff").click(function (e) {
        MUSIC_LIST.thunder_loud1.stop();
        MUSIC_LIST.thunder_loud2.stop();
        $(this).closest("ul").removeClass("clicked");
        return e.preventDefault();
      });
      return $("#loudThunderOn").click(function (e) {
        MUSIC_LIST.thunder_loud1.play({
          position: 0
        });
        $(this).closest("ul").addClass("clicked");
        return e.preventDefault();
      });
    };
    soundManager.setup({
      url: "lib/soundmanager/swf/soundmanager2_flash9.swf",
      preferFlash: false,
      flashVersion: 9,
      flashLoadTimeout: 1500,
      noSWFCache: true,
      debugFlash: false,
      onready: music_player
    });
    soundManager.ontimeout = function (e) {
      soundManager.flashLoadTimeout = 0;
      soundManager.onerror = alert();
      return soundManager.reboot();
    };
    $(".soft_rain .volume .volume_control").slider({
      value: 100,
      min: 0,
      max: 100,
      step: 5,
      slide: function (event, ui) {
        MUSIC_LIST.rain1.setVolume(ui.value);
        return MUSIC_LIST.rain2.setVolume(ui.value);
      }
    });
    $(".rolling_thunder .volume .volume_control").slider({
      value: 100,
      min: 0,
      max: 100,
      step: 5,
      slide: function (event, ui) {
        MUSIC_LIST.thunder_small1.setVolume(ui.value);
        return MUSIC_LIST.thunder_small2.setVolume(ui.value);
      }
    });
    return $(".loud_thunder .volume .volume_control").slider({
      value: 100,
      min: 0,
      max: 100,
      step: 5,
      slide: function (event, ui) {
        MUSIC_LIST.thunder_loud1.setVolume(ui.value);
        return MUSIC_LIST.thunder_loud2.setVolume(ui.value);
      }
    });
  };


  /* 
      background music for mobile 
      Using It is a good day today
   */

  bg_music_mobile = function () {
    var audioSpan;
    audioSpan = 7288;
    return soundManager.setup({
      onready: function () {
        var rain1, rain2, t;
        rain1 = soundManager.createSound({
          id: 'rain1',
          url: 'audio/rainfade_1.mp3',
          autoLoad: true,
          multiShotEvents: true,
          onload: function () {
            return this.play({
              position: 0
            });
          },
          onfinish: function () {
            return this.play({
              position: 0
            });
          }
        });
        rain1.play();
        t = false;
        rain2 = soundManager.createSound({
          id: 'rain2',
          url: 'audio/rainfade_1.mp3',
          autoLoad: true,
          multiShotEvents: true,
          onload: function () {
            return this.play({
              volume: 0,
              position: audioSpan
            });
          },
          onfinish: function () {
            return this.play({
              position: 0
            });
          },
          onplay: function () {
            var e, i, n, r;
            if (t) {
              return false;
            }
            e = 3 * 1e3;
            n = 0;
            r = 100;
            return i = setInterval(function () {
              rain2.setVolume((1 + n) * (r / 12));
              n++;
              if (n === 12) {
                clearInterval(i);
                return t = true;
              }
            }, e / 12);
          }
        });
        return rain2.play();
      }
    });
  };


  /* 
      Detect Whether is a mobile browser, if true , simply play looped music
      http://detectmobilebrowsers.com/
   */

  if (jQuery.browser.mobile === true) {
    bg_image_loading('rain1.jpg');
    bg_music_mobile();
  } else {
    bg_image_loading('yanye3.gif');
    bg_music();
  }

}).call(this);
